Repository openscilab/memor, pull requests merged in 2025-02, with the labels that each got.

#38 Tests
  .github/workflows/test.yml
  memor/__init__.py
  memor/prompt.py
  memor/template.py
  tests/test_custom_prompt_template.py
  tests/test_prompt.py
  tests/test_response.py
Labels: test

#39 Badges
  README.md
Labels: documentation

#40 Rename `CustomPromptTemplate` to `PromptTemplate`
  memor/__init__.py
  memor/functions.py
  memor/params.py
  memor/prompt.py
  memor/template.py
  tests/test_prompt.py
  tests/test_prompt_template.py
Labels: refactoring

#41 Version 0.1
  .github/dependabot.yml
  CHANGELOG.md
Labels: release

#42 Session Structure
  memor/__init__.py
  memor/session.py
  tests/test_prompt_template.py
Labels: enhancement

#43 Session
  memor/session.py
Labels: enhancement

#44 Session Improvement (docstring + validation)
  memor/functions.py
  memor/params.py
  memor/session.py
Labels: documentation, enhancement

#45 `Session` render
  memor/functions.py
  memor/params.py
  memor/session.py
Labels: enhancement

#46 Refactor: Verification + Unification
  memor/functions.py
  memor/params.py
  memor/prompt.py
  memor/session.py
  tests/test_prompt.py
Labels: refactoring

#47 Messages
  memor/functions.py
  memor/response.py
  memor/session.py
Labels: refactoring

#48 Refactor: `validation` and `Response`.`render` function
  README.md
  memor/__init__.py
  memor/functions.py
  memor/params.py
  memor/prompt.py
  memor/response.py
  memor/session.py
  memor/template.py
  tests/test_prompt.py
Labels: enhancement, refactoring

#50 Session Messages
  memor/params.py
  memor/prompt.py
  memor/response.py
  memor/session.py
Labels: enhancement

#51 JSON functions
  README.md
  memor/prompt.py
  memor/response.py
  memor/session.py
  memor/template.py
  tests/test_prompt_template.py
  tests/test_response.py
Labels: refactoring

#52 Session properties
  memor/session.py
Labels: enhancement

#54 Tests Modification
  memor/functions.py
  memor/params.py
  tests/test_prompt.py
  tests/test_prompt_template.py
  tests/test_response.py
  tests/test_session.py
Labels: test

#55 Readme Updated + Minor Edits Applied
  README.md
  memor/functions.py
  memor/params.py
  memor/session.py
  tests/test_response.py
  tests/test_session.py
Labels: documentation, enhancement

#56 Minor edits
  CHANGELOG.md
  README.md
  memor/functions.py
  memor/prompt.py
  tests/test_response.py
Labels: documentation
