Repository openscilab/memor, pull requests merged in 2025-03, with the labels that each got.

#57 Version 0.2
  .github/ISSUE_TEMPLATE/bug_report.yml
  CHANGELOG.md
  README.md
  SECURITY.md
  memor/params.py
  otherfiles/meta.yaml
  otherfiles/version_check.py
  setup.py
Labels: release

#58 Session Length
  CHANGELOG.md
  memor/session.py
  tests/test_session.py
Labels: enhancement

#61 Session/Iter
  CHANGELOG.md
  memor/session.py
  tests/test_session.py
Labels: enhancement

#62 Tokens
  CHANGELOG.md
  memor/prompt.py
  memor/response.py
  memor/template.py
  tests/test_prompt.py
  tests/test_response.py
Labels: enhancement

#70 Session addition methods
  CHANGELOG.md
  memor/prompt.py
  memor/response.py
  memor/session.py
  memor/template.py
  tests/test_session.py
Labels: enhancement

#71 Refactor
  CHANGELOG.md
  memor/params.py
  memor/prompt.py
  memor/response.py
  memor/session.py
  memor/template.py
  tests/test_prompt.py
  tests/test_prompt_template.py
  tests/test_response.py
  tests/test_session.py
Labels: refactoring

#72 Token Validation
  memor/functions.py
  memor/params.py
  memor/prompt.py
  memor/response.py
  tests/test_prompt.py
  tests/test_response.py
Labels: enhancement

#73 Version 0.3
  .github/ISSUE_TEMPLATE/bug_report.yml
  CHANGELOG.md
  README.md
  SECURITY.md
  memor/params.py
  otherfiles/meta.yaml
  otherfiles/version_check.py
  setup.py
Labels: release

#74 Inference Time
  CHANGELOG.md
  README.md
  memor/response.py
  memor/template.py
  tests/test_response.py
Labels: enhancement

#75 Session `__contains__` method
  CHANGELOG.md
  memor/session.py
  tests/test_session.py
Labels: enhancement

#76 Mask/Unmask Feature
  CHANGELOG.md
  memor/session.py
  tests/test_session.py
Labels: enhancement

#77 Session `__getitem__`
  CHANGELOG.md
  memor/session.py
  tests/test_session.py
Labels: enhancement

#78 Response `__len__`
  CHANGELOG.md
  memor/response.py
  tests/test_response.py
Labels: enhancement

#80 Typing Feature Added
  CHANGELOG.md
  memor/functions.py
  memor/prompt.py
  memor/response.py
  memor/session.py
  memor/template.py
  otherfiles/version_check.py
  setup.py
Labels: enhancement

#81 Prompt `__len__`
  CHANGELOG.md
  memor/prompt.py
  memor/session.py
  tests/test_prompt.py
Labels: enhancement

#82 Default Value
  CHANGELOG.md
  memor/prompt.py
  memor/response.py
  tests/test_prompt.py
Labels: bug

#83 Version 0.4
  .github/ISSUE_TEMPLATE/bug_report.yml
  CHANGELOG.md
  README.md
  SECURITY.md
  memor/params.py
  otherfiles/meta.yaml
  otherfiles/version_check.py
  setup.py
Labels: release

#87 Check render
  CHANGELOG.md
  memor/prompt.py
  memor/session.py
  tests/test_prompt.py
  tests/test_session.py
Labels: enhancement

#88 Clear messages
  CHANGELOG.md
  memor/session.py
  tests/test_session.py
Labels: enhancement

#89 Initial check
  CHANGELOG.md
  memor/prompt.py
  memor/session.py
  tests/test_prompt.py
  tests/test_session.py
Labels: enhancement

#90 Tokens Estimation Feature Added to Response, Prompt, Session
  CHANGELOG.md
  memor/__init__.py
  memor/prompt.py
  memor/response.py
  memor/session.py
  memor/tokens_estimator.py
  tests/test_prompt.py
  tests/test_response.py
  tests/test_session.py
  tests/test_token_estimators.py
Labels: enhancement

#93 Minor edits
  .github/CONTRIBUTING.md
  .gitignore
  AUTHORS.md
Labels: documentation, enhancement
