Repository openscilab/memor, pull requests merged in 2025-04, with the labels that each got.

#94 Keywords
  memor/keywords.py
  memor/tokens_estimator.py
  tests/test_session.py
  tests/test_token_estimators.py
Labels: enhancement

#95 Separate Token Estimators For OpenAI Models
  CHANGELOG.md
  memor/tokens_estimator.py
  tests/test_prompt.py
  tests/test_response.py
  tests/test_session.py
  tests/test_token_estimators.py
Labels: enhancement

#96 Prompt Template Details Added to README.md
  CHANGELOG.md
  README.md
Labels: documentation

#97 `Ubuntu-20.04` --> `Ubuntu-22.04`
  .github/workflows/publish_pypi.yml
  .github/workflows/test.yml
  CHANGELOG.md
  README.md
  otherfiles/meta.yaml
  setup.py
Labels: documentation, test

#101 Version 0.5
  .github/ISSUE_TEMPLATE/bug_report.yml
  CHANGELOG.md
  README.md
  SECURITY.md
  memor/params.py
  otherfiles/meta.yaml
  otherfiles/version_check.py
  setup.py
Labels: release

#102 Render Counter
  CHANGELOG.md
  memor/keywords.py
  memor/session.py
  memor/tokens_estimator.py
  tests/test_session.py
Labels: enhancement

#103 LLM Model Enum
  CHANGELOG.md
  memor/__init__.py
  memor/params.py
  memor/response.py
  tests/test_prompt.py
  tests/test_response.py
Labels: enhancement

#105 AI Studio
  CHANGELOG.md
  memor/params.py
  memor/prompt.py
  memor/response.py
  memor/session.py
  tests/test_prompt.py
  tests/test_response.py
  tests/test_session.py
Labels: enhancement

#106 Response ID
  .gitignore
  CHANGELOG.md
  memor/functions.py
  memor/params.py
  memor/response.py
  tests/test_response.py
Labels: enhancement

#107 Prompt ID
  .gitignore
  CHANGELOG.md
  memor/prompt.py
  memor/response.py
  tests/test_prompt.py
Labels: enhancement

#108 ID Methods
  CHANGELOG.md
  memor/session.py
  tests/test_session.py
Labels: enhancement

#109 Minor Changes
  memor/functions.py
  memor/params.py
  memor/session.py
  tests/test_prompt.py
  tests/test_prompt_template.py
  tests/test_response.py
  tests/test_session.py
Labels: enhancement
