Repository openscilab/memor, pull requests merged in 2025-05, with the labels that each got.

#110 Regenerate
  CHANGELOG.md
  memor/prompt.py
  memor/response.py
  tests/test_prompt.py
  tests/test_response.py
Labels: enhancement

#111 Mark Modified
  CHANGELOG.md
  memor/prompt.py
  memor/response.py
  memor/session.py
  memor/template.py
Labels: refactoring

#112 String Format Fixed
  memor/functions.py
  memor/params.py
  memor/session.py
Labels: enhancement

#113 Version 0.6
  .github/ISSUE_TEMPLATE/bug_report.yml
  CHANGELOG.md
  README.md
  SECURITY.md
  memor/params.py
  otherfiles/meta.yaml
  otherfiles/version_check.py
  setup.py
Labels: release

#117 Validation Bug Fixed
  CHANGELOG.md
  memor/functions.py
  memor/params.py
  memor/prompt.py
  memor/response.py
  memor/session.py
  memor/template.py
  tests/test_prompt.py
  tests/test_prompt_template.py
  tests/test_response.py
  tests/test_session.py
Labels: bug

#118 Search
  CHANGELOG.md
  memor/session.py
  tests/test_session.py
Labels: enhancement

#119 AI Studio Warning
  CHANGELOG.md
  memor/params.py
  memor/prompt.py
  memor/response.py
  tests/test_prompt.py
  tests/test_response.py
Labels: enhancement

#120 Validation Bug (Cont.)
  CHANGELOG.md
  memor/prompt.py
  memor/response.py
  memor/session.py
  memor/template.py
  tests/test_prompt.py
  tests/test_prompt_template.py
Labels: bug, enhancement

#121 Refactor
  memor/prompt.py
  memor/response.py
  memor/session.py
  memor/template.py
Labels: refactoring

#122 Messages Status Bug
  CHANGELOG.md
  memor/session.py
  tests/test_session.py
Labels: bug

#123 Null Safety Issue Fixed in Memor Validation
  memor/prompt.py
  memor/response.py
  memor/session.py
  memor/template.py
  tests/test_prompt.py
  tests/test_prompt_template.py
  tests/test_response.py
  tests/test_session.py
Labels: bug

#124 `size` attributes and `get_size` method added to Memor objects
  .gitignore
  CHANGELOG.md
  memor/prompt.py
  memor/response.py
  memor/session.py
  memor/template.py
  tests/test_prompt.py
  tests/test_prompt_template.py
  tests/test_response.py
  tests/test_session.py
Labels: enhancement

#125 Message
  CHANGELOG.md
  memor/message.py
  memor/prompt.py
  memor/response.py
  memor/session.py
  memor/template.py
Labels: refactoring

#126 Fix coverage
  tests/test_prompt.py
Labels: enhancement, test
